### PR TITLE
add functions for admin

### PR DESCRIPTION
**Pull request by jieun1128**
Update allowed number of cpu for each user and user permission

### CODE REVIEW

**Review by math625f — CHANGES_REQUESTED** [review]
The paths you made in routes/admin.py aren't secure, anyone can call them currently without even being logged in.
You need to add `user_id: int = depends(get_current_user_id)` as a parameter to the functions, then it will automatically check if the user is logged in, and you will know the id of the current user
You should probably also check if the user is a sys admin when updating quota.

**Review by math625f — CHANGES_REQUESTED** [review]
Since you already have the user saved in a variable, you can just do `bool(curr_user.sys_admin)`
This works because user has a nullable one-to-one relationship with sys_admin, so if this relationship exists (is not `None`) casting to boolean will be `True`, otherwise if it doesn't exist (if it is `None`) it will be `False`

**Review by math625f — APPROVED** [review]
You could just have done "not x" instead of "x == False", but I will approve this - nice work :)

**Review by kraft-VAERK — APPROVED** [review]
Looks good to me (Y) Good job

**Pull request merged**
