### PR TITLE
Pipeline 1

### PR DESCRIPTION
**Pull request by kraft-VAERK**
Changes in the frontend that push the main branch, will trigger this file which will deploy it to GKE.

### CODE REVIEW

**Comment by kraft-VAERK** [comment]
Moved files from cloudbuild in Gcloud to hidden folder for. No use they have anymore

**Comment by kraft-VAERK** [comment]
Moved docker-compose.yml into the folder where it's needed. Since I don't want an image build if there isn't a change in either the backend or frontend. Therefore a docker-compose.yml for both the backend and frontend. 

One will also be created for minizinc I would imagine

**Comment by kraft-VAERK** [comment]
Test are failed b/c of wrong deployment files, will be changed in another pull-request

**Comment by kraft-VAERK** [comment]
This branch can be deleted after pull request is made. We need to clean up branches.

**Comment by kraft-VAERK** [comment]
Gotta comment again. Path change is to smort

**Review by math625f — APPROVED** [review]
Impressive work

**Pull request merged**
